export const FA_DATATABLE_LOCALIZATION = {
    actions: "عملیات",
    and: "و",
    cancel: "لغو",
    changeFilterMode: "تغییر حالت فیلتر",
    changeSearchMode: "تغییر حالت جستجو",
    clearFilter: "پاک کردن فیلتر",
    clearSearch: "پاک کردن جستجو",
    clearSort: "پاک کردن مرتب سازی",
    clickToCopy: "کلیک برای کپی",
    collapse: "جمع شدن",
    collapseAll: "جمع شدن همه",
    columnActions: "عملیات ستون",
    copiedToClipboard: "کپی شد",
    dropToGroupBy: "رها کردن برای گروه بندی بر اساس {column}",
    edit: "ویرایش",
    expand: "باز شدن",
    expandAll: "باز شدن همه",
    filterArrIncludes: "شامل",
    filterArrIncludesAll: "شامل همه",
    filterArrIncludesSome: "شامل",
    filterBetween: "میان",
    filterBetweenInclusive: "میان با احتساب هر دو",
    filterByColumn: "فیلتر بر اساس {column}",
    filterContains: "شامل",
    filterEmpty: "خالی",
    filterEndsWith: "به پایان می‌رسد با",
    filterEquals: "برابر",
    filterEqualsString: "برابر",
    filterFuzzy: "نزدیک",
    filterGreaterThan: "بزرگتر از",
    filterGreaterThanOrEqualTo: "بزرگتر یا مساوی",
    filterInNumberRange: "میان",
    filterIncludesString: "شامل",
    filterIncludesStringSensitive: "شامل",
    filterLessThan: "کوچکتر از",
    filterLessThanOrEqualTo: "کوچکتر یا مساوی",
    filterMode: "حالت فیلتر: {filterType}",
    filterNotEmpty: "غیر خالی",
    filterNotEquals: "نا برابر",
    filterStartsWith: "شروع می‌شود با",
    filterWeakEquals: "برابر",
    filteringByColumn: "فیلتر بر اساس {column} - {filterType} {filterValue}",
    goToFirstPage: "رفتن به صفحه اول",
    goToLastPage: "رفتن به صفحه آخر",
    goToNextPage: "رفتن به صفحه بعدی",
    goToPreviousPage: "رفتن به صفحه قبلی",
    grab: "گرفتن",
    groupByColumn: "گروه بندی بر اساس {column}",
    groupedBy: "گروه بندی شده بر اساس",
    hideAll: "پنهان کردن همه",
    hideColumn: "پنهان کردن ستون {column}",
    max: "حداکثر",
    min: "حداقل",
    move: "انتقال",
    noRecordsToDisplay: "هیچ رکوردی برای نمایش وجود ندارد",
    noResultsFound: "نتیجه‌ای یافت نشد",
    of: "از",
    or: "یا",
    pinToLeft: "چسباندن به سمت چپ",
    pinToRight: "چسباندن به سمت راست",
    resetColumnSize: "بازنشانی اندازه ستون",
    resetOrder: "بازنشانی ترتیب",
    rowActions: "عملیات ردیف",
    rowNumber: "#",
    rowNumbers: "شماره ردیف",
    rowsPerPage: "ردیف در هر صفحه",
    save: "ذخیره",
    search: "جستجو",
    selectedCountOfRowCountRowsSelected: "{selectedCount} از {rowCount} ردیف انتخاب شده",
    select: "انتخاب",
    showAll: "نمایش همه",
    showAllColumns: "نمایش همه ستون‌ها",
    showHideColumns: "نمایش/مخفی کردن ستون‌ها",
    showHideFilters: "نمایش/مخفی کردن فیلترها",
    showHideSearch: "نمایش/مخفی کردن جستجو",
    sortByColumnAsc: "مرتب سازی بر اساس {column} صعودی",
    sortByColumnDesc: "مرتب سازی بر اساس {column} نزولی",
    sortedByColumnAsc: "مرتب شده بر اساس {column} صعودی",
    sortedByColumnDesc: "مرتب شده بر اساس {column} نزولی",
    thenBy: "، سپس بر اساس ",
    toggleDensity: "تغییر تراکم",
    toggleFullScreen: "تغییر حالت تمام صفحه",
    toggleSelectAll: "انتخاب/عدم انتخاب همه",
    toggleSelectRow: "انتخاب/عدم انتخاب ردیف",
    toggleVisibility: "تغییر پیدا/پنهان",
    ungroupByColumn: "لغو گروه بندی بر اساس {column}",
    unpin: "رها کردن",
    unpinAll: "رها کردن همه",
    unsorted: "بدون مرتب سازی",
};
